#!/usr/bin/env sh
set -eu




### Functions
#############

run_installer() {
    chmod +x "$1" 2>/dev/null || :
    "$1"
}




### ULPE-Install
################

cat << EOF

This script installs ULPE (the "UNIX-Like Portable Environment")
on your system. It will run two installers: ulpe_base, ulpe_plug.
╔═════════╗
║ulpe_base║ Installs the basic packages and configures Bash, Vim
╚═════════╝ and Tmux for you.
╔═════════╗
║ulpe_plug║ Installs additional plugins for your Vim alongside a
╚═════════╝ little vimscript configuration to glue them together.

EOF




### Base & Plug
###############

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" 2>/dev/null && pwd)
BASE_INSTALLER="$ROOT_DIR/ulpe_base"
PLUG_INSTALLER="$ROOT_DIR/ulpe_plug"
# ---
run_installer "$BASE_INSTALLER"; printf "\n"
run_installer "$PLUG_INSTALLER"
