#!/usr/bin/env sh

# This script is intended to be used on a Debian or Debian-based distribution
# and installs a minimal UNIX work environment with some useful packages.




### Functions
#############

sudo_privileges() {
    id -Gn 2>/dev/null | grep -qw "sudo"
}
# ---
ask_user() {
    printf "%s\n" "$1"
    ANS=
    printf "%s" "wish to proceed anyway? [y/N] "
    read -r ANS
    case "$ANS" in
        y | Y | yes | YES) printf "\n%s\n" "setup resumed";;
        *) printf "\n%s\n" "setup interrupted"; exit 1;;
    esac
}
# ---
try_run() {
    if "$@" >/dev/null 2>&1; then
        printf "\n"
    else
        printf ": %s\n" "command failed"
    fi
}
# ---
store_conf() {
    backup_conf() {
        [ -e "$1" ] || [ -L "$1" ] || return
        printf "%s" "removing '$1'"
        if [ -L "$1" ]; then
            try_run unlink "$1"
        else
            try_run mv "$1" "$2/"
        fi
    }
    RESTORE="$HOME/.ulpe_recovery"
    SCRIPT=
    mkdir -p "$RESTORE"
    printf "\n%s\n" "REMOVING BASE SCRIPTS"
    for SCRIPT in \
        .profile \
        .bashrc \
        .bash_logout \
        .vimrc \
        .tmux.conf \
        .local/bin/fetch.sh
    do
        backup_conf "$HOME/$SCRIPT" "$RESTORE"
    done
}




### Checks
##########

if [ "$(id -u)" -eq 0 ]; then
    printf "\n%s"   "This script MUST NOT be run as root since it makes changes to"
    printf "\n%s"   "the \$HOME directory of the \$USER executing it."
    printf "\n%s"   "Run this script as a normal user, you will be asked for a sudo"
    printf "\n%s\n" "password when necessary."
    exit 1
fi
# ---
if [ -d "$HOME/.ulpe_recovery" ]; then
    printf "\n%s"   "WARNING: ULPE already set."
    printf "\n%s\n" "Remove ~/.ulpe_recovery directory and run this script again."
    exit 1
fi




### ULPE-Base
#############

cat << EOF

        __                     __
.--.--.|  |.-----.-----.      |  |--.---.-.-----.-----.
|  |  ||  ||  _  |  -__|      |  _  |  _  |__ --|  -__|
|_____||__||   __|_____| ____ |_____|___._|_____|_____|
           |__|

EOF




### Packages
############

PACKAGES="git wget curl dash bash bash-completion shfmt fzy less file fd-find trash-cli xclip \
wl-clipboard procps x11-xkb-utils tmux vim exuberant-ctags wamerican groff build-essential \
tcc pcc gdb nasm yasm binutils linux-perf strace ltrace pkg-config valgrind indent gcc-doc \
man-db manpages-dev cppman python3-full python3-dev python3-pip pypy3 pypy3-dev pypy3-venv \
python-is-python3 black"
# ---
for PKG in $PACKAGES; do
    if ! apt-get -s install "$PKG" >/dev/null 2>&1; then
        PROBLEMS="${PROBLEMS:+$PROBLEMS }$PKG"
    fi
done
# ---
if [ -n "${PROBLEMS-}" ]; then
    ask_user "these packages might cause issues: '$PROBLEMS'"
fi
# ---
if ! sudo_privileges; then
    ask_user "'$USER' does not have sudo privileges"
fi




### Dependencies
################

if sudo_privileges; then
    sudo sh -c '
        apt-get update &&
        apt-get upgrade -qq -y &&
        { apt-get purge -qq -y vim-tiny || true; }
        for PKG in "$@"; do
            apt-get install -y -qq --no-install-recommends "$PKG" || true
        done
        apt-get -qq -y autoremove --purge &&
        apt-get -qq -y autoclean
    ' _ $PACKAGES || {
        printf "\n%s\n" "packages installation failed"
        exit 1
    }
fi




### Start
#########

store_conf
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )" || exit 1
# ---
printf "\n%s\n" "COPYING BASE SCRIPTS"
for SCRIPT in \
    .profile \
    .bashrc \
    .bash_logout \
    .vimrc \
    .tmux.conf \
    fetch.sh
do
    printf "%s" "copying '$SCRIPT'"
    case $SCRIPT in
        fetch.sh)
            mkdir -p "$HOME/.local/bin/" >/dev/null 2>&1 || continue
            try_run cp "$SCRIPTPATH/base/$SCRIPT" "$HOME/.local/bin/"
            ;;
        *)
            try_run cp "$SCRIPTPATH/base/$SCRIPT" "$HOME/"
            ;;
    esac
done
# ---
if sudo_privileges; then
    sudo chsh -s "$(command -v bash)" "$USER"
fi




### Finish
##########

printf "\n%s\n" "BASE SETUP COMPLETE."
